### ISSUE TITLE
Reintroduce DD_SITE environment variable

### ISSUE THREAD

**Issue by tetienne** [DataDog/datadog-agent-orb#5]
## Describe Request:
With version 0.0.1 it was possible to set the site using DD_SITE env var. With current version 3.0.0, only a string parameter site is exposed. When the setup is used in multiple place, it’s kind of "painful" to each time fill the site. Would be nice to reintroduce DD_SITE.

## Examples:
```
- datadog-agent/setup:
      site: datadoghq.eu
```

to 

```
- datadog-agent/setup

```
We  declare the job calling this command with a context:
```
- test_back:
    context: datadog
```

**Comment by cg14823** [comment]
I have updated the orb to automatically read `DD_SITE` and if not set it fallbacks to whatever was passed to the `site` parameter (or the default). Please let me know if this works for you.

**Comment by tetienne** [comment]
Hi, thx for your reactivity. Sadly, after updating the orb (`datadog-agent: datadog/agent@3.1.0`), and removing the site parameter, the DD_SITE is not taken into account. It was ok with the site parameter.

```
circleci@xxxxxx:~$ env | grep DD                                                               
DD_API_KEY=xxxxxxxxx
DD_ENV=ci                                                                                        
DD_SITE=datadoghq.eu
```

**Comment by cg14823** [comment]
Sorry to hear that I'll have a look.

**Comment by cg14823** [comment]
Should be fixed 😄

**Comment by tetienne** [comment]
This time we are good indeed 🙏
